// Generated by CoffeeScript 1.7.1
(function() {
  var http;

  http = require('http');

  http.createServer(function(req, res) {
    res.writeHead(200, {
      'Content-Type': 'text/plain'
    });
    return res.end('Hello World\n');
  }).listen(3303, '200.21.3.2');

  console.log('Server running at http://200.21.3.2:3303');

}).call(this);
